[package]
name = "zynlex"
version = "0.9.1"
description = "A lightweight desktop browser built for web developers"
authors = ["Zynlex contributors"]
license = "Apache-2.0"
repository = "https://github.com/webtools-dotcom/Zynlex"
homepage = "https://github.com/webtools-dotcom/Zynlex"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "zynlex_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["unstable"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = "2"
tokio = { version = "1", features = ["net", "time", "io-util", "rt"] }
webview2-com = "0.38"
windows-core = "0.61"
windows = { version = "0.61", features = ["Win32_UI_Input_KeyboardAndMouse"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
